version: "3"
services: 
    node1: 
        container_name: node1 
        image: jenkins/ssh-agent
        volumes:
            - ./worker_jenkins_home:/var/jenkins_home
        environment:
            - JENKINS_AGENT_SSH_PUBKEY={ssh-pub-key}